#!/bin/sh
### BEGIN INIT INFO
# Provides:          cilpshare
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: A program that shares your clipboard amongst other machines
# Description:       Clipshare is a program that shares your clipboard with other machines in your network, through an encrypted connection
### END INIT INFO

###############################################################
#                                                             #
#                    CHANGE THE FOLLOWING                     #
#                                                             #
###############################################################

USER=peter
DAEMONPATH=/home/$USER/src/clipshare/clipshare.py
CONFIGFILE= #leave empty if you don't have a custom location
OPTS= #extra options you want to pass, like --debug

###############################################################
#                                                             #
#                 DON'T TOUCH THE FOLLOWING                   #
#                                                             #
###############################################################


# Carry out specific functions when asked to by the system
case "$1" in
	start)
		if [ "$CONFIGFILE" != "" ]
		then
			python -u $DAEMONPATH -c $CONFIGFILE $OPTS start
		else
			python -u $DAEMONPATH $OPTS start
		fi
		;;
	stop)
		python -u $DAEMONPATH stop
		;;
	restart)
		if [ "$CONFIGFILE" != "" ]
		then
			python -u $DAEMONPATH -c $CONFIGFILE $OPTS restart
		else
			python -u $DAEMONPATH $OPTS restart
		fi
		;;
	*)
		echo "Usage: /etc/init.d/clipshare {start|stop|restart}"
		exit 1
		;;
esac

exit 0
